import type { DailyAllocation, Worker } from './types';

import { todayStr } from './utils';

export const DUMMY_CONTRACTORS = [
  'Shree Ganesh Manpower',
  'Om Sai Enterprises',
  'Balaji Industrial Services',
  'TechnoFab Labor Supply',
];

export const DUMMY_DEPARTMENTS = [
  'Welding',
  'Laser',
  'Bending',
  'Painting',
  'Fitting',
  'Fabrication',
  'Assembly',
  'Quality',
  'Maintenance',
  'Store',
  'HR & Admin',
  'Accounts',
];

export const DUMMY_DESIGNATIONS = [
  'HOD / Department Head',
  'Senior Engineer',
  'Floor Supervisor',
  'Quality Inspector',
  'Shift Incharge',
  'Maintenance Engineer',
  'Production Engineer',
  'Store Incharge',
  'HR & Admin Officer',
  'Accounts Officer',
];

export function generateDummyRoster(): Worker[] {
  const createdDate = todayStr();

  const staff: Worker[] = [
    {
      id: 'st_1',
      name: 'Rajesh Deshmukh',
      category: 'staff',
      department: 'Welding',
      designation: 'HOD / Department Head',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_2',
      name: 'Amit Patil',
      category: 'staff',
      department: 'Laser',
      designation: 'Senior Engineer',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_3',
      name: 'Pooja Kulkarni',
      category: 'staff',
      department: 'Quality',
      designation: 'Quality Inspector',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_4',
      name: 'Vikas Sharma',
      category: 'staff',
      department: 'Fabrication',
      designation: 'Floor Supervisor',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_5',
      name: 'Sunil Jagtap',
      category: 'staff',
      department: 'Bending',
      designation: 'Shift Incharge',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_6',
      name: 'Deepak Shinde',
      category: 'staff',
      department: 'Maintenance',
      designation: 'Maintenance Engineer',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_7',
      name: 'Neha Gaikwad',
      category: 'staff',
      department: 'HR & Admin',
      designation: 'HR & Admin Officer',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'st_8',
      name: 'Pravin More',
      category: 'staff',
      department: 'Store',
      designation: 'Store Incharge',
      unit: 'UNIT III',
      status: 'active',
      createdAt: createdDate,
    },
  ];

  const labor: Worker[] = [
    // Shree Ganesh Manpower (6)
    {
      id: 'lb_sg_1',
      name: 'Santosh Gaikwad',
      category: 'labor',
      contractor: 'Shree Ganesh Manpower',
      department: 'Welding',
      subCategory: 'Welder',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_sg_2',
      name: 'Datta Kale',
      category: 'labor',
      contractor: 'Shree Ganesh Manpower',
      department: 'Welding',
      subCategory: 'Welder',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_sg_3',
      name: 'Sachin Jadhav',
      category: 'labor',
      contractor: 'Shree Ganesh Manpower',
      department: 'Welding',
      subCategory: 'Helper',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_sg_4',
      name: 'Rahul Kamble',
      category: 'labor',
      contractor: 'Shree Ganesh Manpower',
      department: 'Laser',
      subCategory: 'Operator',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_sg_5',
      name: 'Balu Thite',
      category: 'labor',
      contractor: 'Shree Ganesh Manpower',
      department: 'Fabrication',
      subCategory: 'Helper',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_sg_6',
      name: 'Popat Shinde',
      category: 'labor',
      contractor: 'Shree Ganesh Manpower',
      department: 'Welding',
      subCategory: 'Welder',
      unit: 'UNIT I',
      status: 'debarred', // Sample debarred record
      createdAt: createdDate,
    },

    // Om Sai Enterprises (5)
    {
      id: 'lb_os_1',
      name: 'Nitin Chavan',
      category: 'labor',
      contractor: 'Om Sai Enterprises',
      department: 'Laser',
      subCategory: 'Operator',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_os_2',
      name: 'Vishal Gorde',
      category: 'labor',
      contractor: 'Om Sai Enterprises',
      department: 'Laser',
      subCategory: 'Helper',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_os_3',
      name: 'Ganesh Waghmare',
      category: 'labor',
      contractor: 'Om Sai Enterprises',
      department: 'Bending',
      subCategory: 'Operator',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_os_4',
      name: 'Akash Bhosale',
      category: 'labor',
      contractor: 'Om Sai Enterprises',
      department: 'Bending',
      subCategory: 'Helper',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_os_5',
      name: 'Kishor Mane',
      category: 'labor',
      contractor: 'Om Sai Enterprises',
      department: 'Painting',
      subCategory: 'Operator',
      unit: 'UNIT I',
      status: 'inactive', // Sample left company record
      createdAt: createdDate,
    },

    // Balaji Industrial Services (5)
    {
      id: 'lb_bi_1',
      name: 'Somnath Giram',
      category: 'labor',
      contractor: 'Balaji Industrial Services',
      department: 'Painting',
      subCategory: 'Operator',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_bi_2',
      name: 'Pandurang Lande',
      category: 'labor',
      contractor: 'Balaji Industrial Services',
      department: 'Painting',
      subCategory: 'Helper',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_bi_3',
      name: 'Mahesh Thorat',
      category: 'labor',
      contractor: 'Balaji Industrial Services',
      department: 'Fitting',
      subCategory: 'Welder',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_bi_4',
      name: 'Tukaram Pawar',
      category: 'labor',
      contractor: 'Balaji Industrial Services',
      department: 'Fitting',
      subCategory: 'Helper',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_bi_5',
      name: 'Sandip Salve',
      category: 'labor',
      contractor: 'Balaji Industrial Services',
      department: 'Housekeeping',
      subCategory: 'Housekeeping',
      unit: 'UNIT III',
      status: 'active',
      createdAt: createdDate,
    },

    // TechnoFab Labor Supply (4)
    {
      id: 'lb_tf_1',
      name: 'Anil Sonawane',
      category: 'labor',
      contractor: 'TechnoFab Labor Supply',
      department: 'Assembly',
      subCategory: 'Operator',
      unit: 'UNIT III',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_tf_2',
      name: 'Ajay Kadam',
      category: 'labor',
      contractor: 'TechnoFab Labor Supply',
      department: 'Assembly',
      subCategory: 'Helper',
      unit: 'UNIT III',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_tf_3',
      name: 'Sambhaji Shinde',
      category: 'labor',
      contractor: 'TechnoFab Labor Supply',
      department: 'Fabrication',
      subCategory: 'Welder',
      unit: 'UNIT II',
      status: 'active',
      createdAt: createdDate,
    },
    {
      id: 'lb_tf_4',
      name: 'Rohan Gaikwad',
      category: 'labor',
      contractor: 'TechnoFab Labor Supply',
      department: 'Maintenance',
      subCategory: 'Helper',
      unit: 'UNIT I',
      status: 'active',
      createdAt: createdDate,
    },
  ];

  return [...staff, ...labor];
}

export function generateDummyDailyAllocations(): Record<string, DailyAllocation> {
  return {
    // Staff attendance
    st_1: {
      present: true,
      department: 'Welding',
      unit: 'UNIT I',
      shift: 'Day',
      supervisor: 'Self (HOD)',
      checkInTime: '08:15 AM',
      remarks: 'Morning shift head',
    },
    st_2: {
      present: true,
      department: 'Laser',
      unit: 'UNIT I',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
      checkInTime: '08:24 AM',
    },
    st_3: {
      present: true,
      department: 'Quality',
      unit: 'UNIT I',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
      checkInTime: '08:28 AM',
    },
    st_4: {
      present: true,
      department: 'Fabrication',
      unit: 'UNIT II',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
      checkInTime: '08:35 AM',
    },
    st_5: {
      present: true,
      department: 'Bending',
      unit: 'UNIT II',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
      checkInTime: '08:40 AM',
    },
    st_6: {
      present: true,
      department: 'Maintenance',
      unit: 'UNIT I',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
      checkInTime: '08:10 AM',
      remarks: 'Machine 4 preventative maintenance',
    },
    st_7: {
      present: true,
      department: 'HR & Admin',
      unit: 'UNIT I',
      shift: 'Day',
      supervisor: 'Management',
      checkInTime: '08:45 AM',
    },
    st_8: {
      present: false, // On planned leave
      department: 'Store',
      unit: 'UNIT III',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
      remarks: 'Planned casual leave',
    },

    // Labor attendance
    lb_sg_1: {
      present: true,
      department: 'Welding',
      unit: 'UNIT I',
      subCategory: 'Welder',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
    },
    lb_sg_2: {
      present: true,
      department: 'Welding',
      unit: 'UNIT I',
      subCategory: 'Welder',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
    },
    lb_sg_3: {
      present: true,
      department: 'Welding',
      unit: 'UNIT I',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
    },
    lb_sg_4: {
      present: true,
      department: 'Laser',
      unit: 'UNIT I',
      subCategory: 'Operator',
      shift: 'Night', // Night shift sample
      supervisor: 'Amit Patil',
      remarks: 'Night shift roster',
    },
    lb_sg_5: {
      present: false, // Absent
      department: 'Fabrication',
      unit: 'UNIT II',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Vikas Sharma',
    },

    // Om Sai Enterprises
    lb_os_1: {
      present: true,
      department: 'Laser',
      unit: 'UNIT I',
      subCategory: 'Operator',
      shift: 'Day',
      supervisor: 'Amit Patil',
    },
    lb_os_2: {
      present: true,
      department: 'Laser',
      unit: 'UNIT I',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Amit Patil',
    },
    lb_os_3: {
      present: true,
      department: 'Bending',
      unit: 'UNIT II',
      subCategory: 'Operator',
      shift: 'Day',
      supervisor: 'Sunil Jagtap',
    },
    lb_os_4: {
      present: true,
      department: 'Bending',
      unit: 'UNIT II',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Sunil Jagtap',
    },

    // Balaji Industrial Services
    lb_bi_1: {
      present: true,
      department: 'Painting',
      unit: 'UNIT I',
      subCategory: 'Operator',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
    },
    lb_bi_2: {
      present: true,
      department: 'Painting',
      unit: 'UNIT I',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
    },
    lb_bi_3: {
      present: true,
      department: 'Fitting',
      unit: 'UNIT II',
      subCategory: 'Welder',
      shift: 'Day',
      supervisor: 'Vikas Sharma',
    },
    lb_bi_4: {
      present: false, // Absent
      department: 'Fitting',
      unit: 'UNIT II',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Vikas Sharma',
    },
    lb_bi_5: {
      present: true,
      department: 'Housekeeping',
      unit: 'UNIT III',
      subCategory: 'Housekeeping',
      shift: 'Day',
      supervisor: 'Rajesh Deshmukh',
    },

    // TechnoFab Labor Supply
    lb_tf_1: {
      present: true,
      department: 'Assembly',
      unit: 'UNIT III',
      subCategory: 'Operator',
      shift: 'Day',
      supervisor: 'Pravin More',
    },
    lb_tf_2: {
      present: true,
      department: 'Assembly',
      unit: 'UNIT III',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Pravin More',
    },
    lb_tf_3: {
      present: true,
      department: 'Fabrication',
      unit: 'UNIT II',
      subCategory: 'Welder',
      shift: 'Night', // Night shift sample
      supervisor: 'Vikas Sharma',
    },
    lb_tf_4: {
      present: true,
      department: 'Maintenance',
      unit: 'UNIT I',
      subCategory: 'Helper',
      shift: 'Day',
      supervisor: 'Deepak Shinde',
    },
  };
}
